import { fetchTable } from "@/lib/db";
import { PageHeader } from "@/components/ui";
import { WeeklyReportView, type ReportPayload } from "@/components/WeeklyReportView";
import { PrintButton } from "@/components/PrintButton";
import Link from "next/link";

export const dynamic = "force-dynamic";

export interface ReportRow {
  report_id: number;
  week_label: string;
  period_start: string;
  period_end: string;
  generated_at: string;
  payload: ReportPayload;
}

export default async function WeeklyPage() {
  const reports = await fetchTable<ReportRow>(
    "ac_reports", "select=*&order=period_end.desc&limit=30");
  const latest = reports[0];

  return (
    <div>
      <div className="flex flex-wrap items-start justify-between gap-3">
        <PageHeader
          title="Weekly report"
          description={latest
            ? `Latest analyst report — generated ${latest.generated_at?.slice(0, 16).replace("T", " ")} UTC. Archived weekly.`
            : "No archived report yet."}
        />
        {latest && <PrintButton />}
      </div>

      {!latest ? (
        <p className="text-sm text-slate-600">
          The first report is generated by the Monday pipeline run — or trigger it manually:
          GitHub → Actions → weekly-digest → Run workflow (or run
          scripts/generate_weekly_report.py locally).
        </p>
      ) : (
        <WeeklyReportView
          payload={latest.payload}
          weekLabel={latest.week_label}
          periodStart={latest.period_start}
          periodEnd={latest.period_end}
        />
      )}

      {reports.length > 1 && (
        <section className="mt-10 print:hidden">
          <h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">
            Report archive
          </h2>
          <div className="flex flex-wrap gap-2">
            {reports.slice(1).map((r) => (
              <Link key={r.report_id} href={`/weekly/${r.week_label}`}
                    className="rounded border border-slate-800 bg-slate-900/40 px-3 py-1.5 text-xs text-slate-400 hover:border-slate-600 hover:text-slate-200">
                {r.week_label} <span className="text-slate-600">({r.period_start} → {r.period_end})</span>
              </Link>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
